(defun block-of-text (file row column)
	(with-open-file (stream file :direction :input)
		(do ((s (read-char stream nil nil) (read-char stream nil nil))
			(curc 0 (1+ curc))
			(curr 0))
		    ((not s))
		   (if (<= 33 (char-code s) 126)
		   		(format t "~a" s)
		   		(format t "."))
		   (when (>= curc column)
				(format t "~%")
				(setf curc 0)
				(incf curr)
				(when (>= curr row)
					(format t "~%")
					(setf curr 0))))))